url: virtuozjack.github.io
baseurl: "/VirtuozJack"

source: source
destination: _site

sass:
  sass_dir: _sass
  style: compressed # expanded

# SEO settings
title: Jacek Marzec - Portfolio 
description: "Open for job position."
keywords: "Jacek, Marzec, job, praca, SEO, web"


google_analytics: 
repo: https://github.com/VirtuozJack
disqus_shortname: 
disqus_site_shortname: 

# Author settings
author:
  name: Jacek Marzec
  job: Developer
  bio: "I’m a recent Computer Science graduate from WSEI Lublin College. Below you may find out my projects."
  thumb: /images/author.jpg
  email: wirtuoz.1985rok@gmail.com
  url: https://github.com/VirtuozJack
  github: https://github.com/VirtuozJack
  twitter: 
  facebook: https://www.facebook.com/jackjack534
  linkedin: 

# navbar pages
navbar:
  - slug: about
    title: About
  - slug: icons
    title: Icons

exclude: ["config.rb", "src", "Gemfile", "Gemfile.lock", "package.json","README.md", "Rakefile"]
